### ISSUE TITLE
请问一下如何实现那个艺术二维码呢，可不可以给我一个例子呢，谢谢

### ISSUE THREAD

**Issue by fenglijunnb** [bronze1man/kmgQrcode#2]
![image](https://user-images.githubusercontent.com/48191768/77511876-e8f4a980-6eac-11ea-9d25-9b5b81f92c7a.png)
![image](https://user-images.githubusercontent.com/48191768/77511891-ee51f400-6eac-11ea-9060-52739308575c.png)
![it399 com qrcode2](https://user-images.githubusercontent.com/48191768/77511900-f14ce480-6eac-11ea-85c6-50abddd8a2d1.jpg)

**Comment by bronze1man** [comment]
这个库只能生成两色的二维码,其他的都不支持.也许你可以先生成一个两色的二维码,然后再去ps里面改一改?

**Comment by fenglijunnb** [comment]
如果是需要ps的话，那就没有必要自己生成二维码了，网上的工具较多，但是艺术类的需要掏钱，ps技术不太行，所以想向你了解一下有没有那种艺术的库呢

**Comment by bronze1man** [comment]
没有.
感觉那个第二张点点的很容易直接用代码for循环生成.
其他的看上去算法很复杂.

**Comment by fenglijunnb** [comment]
那么第二张的循环，具体应该是怎么写呢，我技术比较菜，请教一下你

**Comment by bronze1man** [comment]
大概思路是:
* 先尝试生成一张2色的每个二维码的元素是1x1 大小(一个像素)的, 
* 然后把这个二维码一个像素一个像素的遍历一下,根据这边图片的颜色,向另一张图片里面的类似位置放一个圆过去.
* 然后就可以得到类似的图片了.

**Comment by fenglijunnb** [comment]
那请问一下，你有没有兴趣搞一搞这个艺术类的二维码呢，如果有的话，你可以上传上来，我会时刻关注你的

**Comment by bronze1man** [comment]
@fenglijunnb https://qrcode.ai/ 这个也许可以解决你的问题。
